### ISSUE TITLE
Livonia map is BLANK!!!

### ISSUE THREAD

**Issue by neil501** [CypherMediaGIT/DayZCOMode-Livonia-Edition#2] opened 2020-02-24 05:44 UTC
When i load up the livonia map i can see zombies and there are tons of items just floating everywhere but the map has no trees,no buildings only zombies and floating parts thats it! After 5 minutes the whole thing just crashes. Is there anything that i can try to fix this? Playing online the map is fine it's only the offline where it gets all messed up. Please let me know if you can figure something thank you!

**Comment by CypherMediaGIT** [comment] 2020-02-25 13:07
Hey I tested and Livonia loaded up fine for me, when you run Livonia online you load the map from a server, when you run offline you are loading the whole map and DayZ game from your PC, that’s why it takes longer to load and why it works fine for you online, is your PC able to handle loading in locally?

**Comment by neil501** [comment] 2020-02-29 20:27
yeah i have a intel i7-8700 3.20ghz 16gb ram  nvidia geforce gtx 1060 3gb video card 1TB solid hd 4tb 2nd drive I got this last year gaming computer i dont have a problem playing anything, yeah online livonia comes up no problem but offline it's always the same bare! and if i spawn and use a car? the game crashes! I have no such issues with the charnus map. Is livonia map bigger? If i turned down all the grapics and everything to lowest levels you think the game might work? Is that the problem?

**Comment by neil501** [comment] 2020-03-02 13:24
I guess what i just dont get is how can i play the chenarus map offline with everything maxed out and it plays great offline but the livonia map with everything either disabled or on lowest settings the map comes up blank. I would think they are the same? Right? Unless livonia is far larger than i thought or has a much bigger map with more details...... I think it has to be something simple that was overlooked why one map works and one don't if you can think of anything please i'm all ears

**Comment by CypherMediaGIT** [comment] 2020-03-02 13:35
I’m going to be retesting the whole offline map tonight on a fresh install of windows and DayZ and fresh install of Livonia offline mode, if I can’t replicate your issue and it works fine for me, then I can’t suggest much else as so far I can’t replicate it

**Comment by CypherMediaGIT** [comment] 2020-03-03 11:02
Ok I have tested on a fresh install of windows and of DayZ and still I can’t replicate your issue so the problem doesn’t stem from the Mod it is something on your end, Livonia offline has no issues that I can find, buildings load fine for me and I don’t have floating items, that is caused by buildings not loading in and the loot
Floating where a buildings floor would be, this issue will now be closed as it’s not an issue with Livonia offline

**Closed as completed by CypherMediaGIT** 2020-03-03 11:02 UTC
